import { User } from "../../domain/entities/User";

import { UserModel } from "./schemas/UserSchema";

export class MongoUserRepository {
  async save(user) {
    const userDoc = new UserModel({
      _id: user.id, // We trust the ID generated by the application, or let Mongo generate?
      // Domain says "User" has an ID. Use Case generated "crypto.randomUUID".
      // So we use that ID.
      email: user.email,
      passwordHash: user.passwordHash,
      role: user.role,
      trustScore: user.trustScore,
      completedTransactions: user.completedTransactions,
      cancelledBookings: user.cancelledBookings,
      averageRating: user.averageRating,
      profile: user.profile
    });
    await userDoc.save();
    return this.mapToEntity(userDoc);
  }

  async findByEmail(email) {
    const doc = await UserModel.findOne({ email });
    return doc ? this.mapToEntity(doc) : null;
  }

  async findById(id) {
    const doc = await UserModel.findById(id);
    return doc ? this.mapToEntity(doc) : null;
  }

  async update(user) {
    const doc = await UserModel.findByIdAndUpdate(
      user.id,
      {
        email: user.email,
        passwordHash: user.passwordHash,
        role: user.role,
        trustScore: user.trustScore,
        completedTransactions: user.completedTransactions,
        cancelledBookings: user.cancelledBookings,
        averageRating: user.averageRating,
        profile: user.profile
      },
      { new: true }
    );
    if (!doc) throw new Error("User not found for update");
    return this.mapToEntity(doc);
  }

  mapToEntity(doc) {
    return new User(
      doc._id.toString(),
      doc.email,
      doc.passwordHash,
      doc.role,
      doc.trustScore,
      doc.completedTransactions,
      doc.cancelledBookings,
      doc.averageRating,
      doc.profile
    );
  }
}